# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - 5001:5000
    depends_on:
      mariadb:
        condition: service_healthy
  frontend:
    image: frontend
    build:
      context: Frontend/
      dockerfile: Dockerfile
    ports:
      - 3001:3000
  proxy:
    image: nginx
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:80
    depends_on:
      - frontend
      - backend
  mariadb:
    image: mariadbcustom
    build:
      context: ./MariaDB
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${MARIADB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
  sphinx:
    image: sphinx-search
    build:
      context: ./SphinxSearch
      dockerfile: Dockerfile
    ports:
      - 9311:9306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
