# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - 5001:5000
  frontend:
    image: frontend
    build:
      context: Frontend/
      dockerfile: Dockerfile
    ports:
      - 3001:3000
  proxy:
    image: nginx
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:80
